# Generated by Django 6.0.3 on 2026-04-03 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0001_initial'),
        ('petani', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funding',
            new_name='Donasi',
        ),
    ]
