# Generated by Django 6.0.3 on 2026-04-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0002_rename_funding_donasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='donasi',
            name='dana_terkumpul',
            field=models.IntegerField(default=0),
        ),
    ]
