# Generated by Django 6.0.3 on 2026-04-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0003_donasi_dana_terkumpul'),
        ('petani', '0016_kebutuhanbarang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonasiBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang_custom', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dikirim', 'Dikirim')], default='diajukan', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('donatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kebutuhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petani.kebutuhanbarang')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petani.project')),
            ],
        ),
    ]
