# Generated by Django 6.0.3 on 2026-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0004_donasibarang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasi',
            name='dana_terkumpul',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
