# Generated by Django 6.0.3 on 2026-05-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0006_donasi_keuntungan_d'),
        ('petani', '0021_kebutuhanbarang_harga_satuan_kebutuhanbarang_satuan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donasibarang',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='donasibarang',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='donasibarang',
            name='kebutuhan',
        ),
        migrations.RemoveField(
            model_name='donasibarang',
            name='nama_barang_custom',
        ),
        migrations.CreateModel(
            name='DonasiBarangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('donasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='donatur.donasibarang')),
                ('kebutuhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petani.kebutuhanbarang')),
            ],
        ),
    ]
