# Generated by Django 6.0.3 on 2026-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foto_lahan',
            field=models.ImageField(default=1, upload_to='lahan/'),
            preserve_default=False,
        ),
    ]
