# Generated by Django 6.0.3 on 2026-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0002_project_foto_lahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('aktif', 'Sedang Didanai'), ('selesai', 'Selesai')], default='pending', max_length=10),
        ),
    ]
