# Generated by Django 6.0.3 on 2026-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0003_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kebutuhan',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
