# Generated by Django 6.0.3 on 2026-04-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0004_project_kebutuhan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dana_terkumpul',
            new_name='bagi_hasil_donatur',
        ),
        migrations.AddField(
            model_name='project',
            name='bagi_hasil_petani',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimasi_hasil',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='estimasi_panen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimasi_pendapatan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='lokasi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='luas_lahan',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='foto_lahan',
            field=models.ImageField(null=True, upload_to='lahan/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='kebutuhan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_dana',
            field=models.IntegerField(null=True),
        ),
    ]
