# Generated by Django 6.0.3 on 2026-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0005_rename_dana_terkumpul_project_bagi_hasil_donatur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimasi_hasil',
            field=models.IntegerField(null=True),
        ),
    ]
