# Generated by Django 6.0.3 on 2026-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0006_alter_project_estimasi_hasil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bagi_hasil_donatur',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bagi_hasil_petani',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimasi_pendapatan',
        ),
        migrations.AlterField(
            model_name='project',
            name='estimasi_panen',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tanggal_mulai',
            field=models.DateField(null=True),
        ),
    ]
