# Generated by Django 6.0.3 on 2026-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0007_remove_project_bagi_hasil_donatur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dana_terkumpul',
            field=models.IntegerField(default=0),
        ),
    ]
