# Generated by Django 6.0.3 on 2026-04-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0008_project_dana_terkumpul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('jumlah_pengeluaran', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bukti', models.ImageField(blank=True, null=True, upload_to='bukti_laporan/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='petani.project')),
            ],
        ),
    ]
