# Generated by Django 6.0.3 on 2026-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0009_laporan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='estimasi_panen',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tanggal_mulai',
        ),
        migrations.AddField(
            model_name='project',
            name='berapa_bulan',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
