# Generated by Django 6.0.3 on 2026-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0010_remove_project_estimasi_panen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
