# Generated by Django 6.0.3 on 2026-04-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0011_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
