# Generated by Django 6.0.3 on 2026-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0012_remove_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alat',
            field=models.CharField(choices=[('ca', 'Cangkul'), ('pu', 'Pupuk'), ('se', 'Sekop'), ('pH', 'pH Meter Tanah'), ('dr', 'Drone')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
