# Generated by Django 6.0.3 on 2026-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0013_project_alat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='alat',
        ),
        migrations.AddField(
            model_name='project',
            name='alat',
            field=models.ManyToManyField(to='petani.alat'),
        ),
    ]
