# Generated by Django 6.0.3 on 2026-04-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0014_alat_remove_project_alat_project_alat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='alat',
        ),
        migrations.DeleteModel(
            name='Alat',
        ),
    ]
