# Generated by Django 6.0.3 on 2026-04-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0015_remove_project_alat_delete_alat'),
    ]

    operations = [
        migrations.CreateModel(
            name='KebutuhanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah_dibutuhkan', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kebutuhan_barang', to='petani.project')),
            ],
        ),
    ]
