# Generated by Django 6.0.3 on 2026-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0016_kebutuhanbarang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dana_terkumpul',
        ),
        migrations.AlterField(
            model_name='project',
            name='target_dana',
            field=models.IntegerField(default=0),
        ),
    ]
