# Generated by Django 6.0.3 on 2026-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0016_kebutuhanbarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_hp',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
