# Generated by Django 6.0.3 on 2026-04-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0017_project_no_hp'),
        ('petani', '0017_remove_project_dana_terkumpul_and_more'),
    ]

    operations = [
    ]
