# Generated by Django 6.0.3 on 2026-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0018_merge_20260428_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='target_dana',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
