# Generated by Django 6.0.3 on 2026-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0020_project_keuntungan_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebutuhanbarang',
            name='harga_satuan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kebutuhanbarang',
            name='satuan',
            field=models.CharField(default='item', max_length=50),
        ),
    ]
