# Generated by Django 6.0.3 on 2026-05-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0021_kebutuhanbarang_harga_satuan_kebutuhanbarang_satuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilPanen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pendapatan', models.DecimalField(decimal_places=0, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('bukti_panen', models.ImageField(blank=True, null=True, upload_to='hasil_panen/')),
                ('tanggal_panen', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_panen', to='petani.project')),
            ],
        ),
    ]
