# Generated by Django 6.0.3 on 2026-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0022_hasilpanen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilpanen',
            name='bukti_panen',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_laporan/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='kebutuhan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
