# Generated by Django 6.0.3 on 2026-04-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Class icon Phosphor, contoh: ph-plant', max_length=100, null=True)),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampil di halaman edukasi')),
            ],
            options={
                'verbose_name_plural': 'Kategori Edukasi',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='MateriEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('konten', models.TextField(help_text='Format HTML/Text untuk isi materi')),
                ('target_role', models.CharField(choices=[('semua', 'Umum (Petani & Investor)'), ('petani', 'Khusus Petani Milenial'), ('donatur', 'Khusus Investor')], default='semua', max_length=20)),
                ('waktu_baca', models.IntegerField(default=5, help_text='Estimasi waktu baca (menit)')),
                ('urutan', models.IntegerField(default=0, help_text='Urutan materi di dalam kategori')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='edukasi.kategoriedukasi')),
            ],
            options={
                'verbose_name_plural': 'Materi Edukasi',
                'ordering': ['kategori', 'urutan'],
            },
        ),
    ]
